name: cromaAI
dependencies:
  - pip
  - python=3.6.9
  - conda-forge::beautifulsoup4
  - conda-forge::mongoengine
  - mongodb
  - requests
  - ipython
  - gensim
  - spacy
  - numpy
  - pytorch::faiss-cpu
  - pip:
    - schema
    - flask
    - flask-mongoengine
    - textacy
    - fast-autocomplete